server:
  port: 8081

recorder:
  url: http://localhost:8080

accounting:
  url: http://localhost:8082

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9494/auth/realms/t1
        registration:
          keycloak:
            provider: keycloak
            client-id: c1
            client-secret: 591fc107-2fa1-4b58-b1d4-293187c628f3
            scope: offline_access,profile,email,address,phone,roles,web-origins,microprofile-jwt

  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie

  session:
    store-type: redis

  redis:
    host: localhost
    port: 6379
    password:

login:
  redirect: http://localhost:3000/success-login